#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import json

from nomad.datamodel.metainfo.basesections import Process
from nomad.datamodel.data import EntryData
from typing import (
    TYPE_CHECKING,
)
from nomad.metainfo import (
    Package,
    Quantity,
    Section,
)
from nomad.datamodel.data import (
    EntryData,
    ArchiveSection,
)
if TYPE_CHECKING:
    from nomad.datamodel.datamodel import (
        EntryArchive,
    )
    from structlog.stdlib import (
        BoundLogger,
    )

m_package = Package(name='Run example')


class Run(Process, EntryData, ArchiveSection):
    '''
    Class autogenerated from yaml schema.
    '''
    m_def = Section()
    run_name = Quantity(
        type=str,
        description='Name of the run',
        default="",
    )
    project = Quantity(
        type=str,
        description='Project of the run',
        default="",
    )
    workpackage = Quantity(
        type=str,
        description='some description',
        default="",
    )
    run_description = Quantity(
        type=str,
        description='Description of the run',
        default="",
    )
    author = Quantity(
        type=str,
        description='Author of the run',
        default="",
    )
    cost_model = Quantity(
        type=str,
        description='some Cost model description',
        default="",
    )
    start_date = Quantity(
        type=str,
        description='Start date of the run',
        default="",
    )
    generated_on = Quantity(
        type=str,
        description='Date of the generation of the report',
        default="",
    )

    data_file = Quantity(
        type=str,
        description='The recipe file for the rie process.',
        a_eln={
            'component': 'FileEditQuantity',
        },
    )

    def normalize(self, archive: 'EntryArchive', logger: 'BoundLogger') -> None:
        '''
        The normalizer for the `Run` class.

        Args:
            archive (EntryArchive): The archive containing the section that is being
            normalized.
            logger (BoundLogger): A structlog logger.
        '''
        super().normalize(archive, logger)


        if self.data_file:
            with archive.m_context.raw_file(self.data_file) as file:
                data_dict = json.load(file)
            
            # The following line could be interesting if default values are set, 
            # since it would overwrite them only if the key is really present in the data_dict
            #
            # self.run_name = data_dict.get('run_name', self.run_name)
            
            self.run_name = data_dict['run_name']
            self.project = data_dict['project']
            self.workpackage = data_dict['workpackage']
            self.run_description = data_dict['run_description']
            self.author = data_dict['author']
            self.cost_model = data_dict['cost_model']
            self.start_date = data_dict['start_date']
            self.generated_on = data_dict['generated_on']



m_package.__init_metainfo__()
